[package]
name = "rosehost"
version = "0.1.1"
edition = "2021"

[dependencies]
httparse = "1.10.0"
log = "0.4.25"
ekero = { git = "https://github.com/rosewareorg/ekero.git" }
clang_log = "2.0.5"

[dev-dependencies]
clang_log = "2.0.5"
